'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import type { Components } from "@repo/app-shell/dist/components";
import { AppFooter as AppFooterElement } from "@repo/app-shell/dist/components/app-footer.js";
import { AppHeader as AppHeaderElement } from "@repo/app-shell/dist/components/app-header.js";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@repo/app-shell/react/client";

export const serializeShadowRoot: SerializeShadowRootOptions = "declarative-shadow-dom";

export type AppFooterEvents = NonNullable<unknown>;

export const AppFooter: StencilReactComponent<AppFooterElement, AppFooterEvents, Components.AppFooter> = /*@__PURE__*/ createComponent<AppFooterElement, AppFooterEvents, Components.AppFooter>({
    tagName: 'app-footer',
    properties: { year: 'year' },
    hydrateModule: typeof window === 'undefined' ? (import('@repo/app-shell/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.AppFooter as StencilReactComponent<AppFooterElement, AppFooterEvents, Components.AppFooter>,
    serializeShadowRoot
});

export type AppHeaderEvents = NonNullable<unknown>;

export const AppHeader: StencilReactComponent<AppHeaderElement, AppHeaderEvents, Components.AppHeader> = /*@__PURE__*/ createComponent<AppHeaderElement, AppHeaderEvents, Components.AppHeader>({
    tagName: 'app-header',
    properties: {
        activeZone: 'active-zone',
        userLoggedIn: 'user-logged-in'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@repo/app-shell/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.AppHeader as StencilReactComponent<AppHeaderElement, AppHeaderEvents, Components.AppHeader>,
    serializeShadowRoot
});
