'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@repo/app-shell/dist/components";
import { AppFooter as AppFooterElement, defineCustomElement as defineAppFooter } from "@repo/app-shell/dist/components/app-footer.js";
import { AppHeader as AppHeaderElement, defineCustomElement as defineAppHeader } from "@repo/app-shell/dist/components/app-header.js";

export type AppFooterEvents = NonNullable<unknown>;

export const AppFooter: StencilReactComponent<AppFooterElement, AppFooterEvents, Components.AppFooter> = /*@__PURE__*/ createComponent<AppFooterElement, AppFooterEvents, Components.AppFooter>({
    tagName: 'app-footer',
    elementClass: AppFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as AppFooterEvents,
    defineCustomElement: defineAppFooter
});

export type AppHeaderEvents = NonNullable<unknown>;

export const AppHeader: StencilReactComponent<AppHeaderElement, AppHeaderEvents, Components.AppHeader> = /*@__PURE__*/ createComponent<AppHeaderElement, AppHeaderEvents, Components.AppHeader>({
    tagName: 'app-header',
    elementClass: AppHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as AppHeaderEvents,
    defineCustomElement: defineAppHeader
});
