/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFooter {
        /**
          * Ano exibido no aviso de copyright. Ver `CURRENT_YEAR`.
          * @default CURRENT_YEAR
         */
        "year": number;
    }
    interface AppHeader {
        /**
          * @default 'storefront'
         */
        "activeZone": 'storefront' | 'blog';
        /**
          * @default false
         */
        "userLoggedIn": boolean;
    }
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
        /**
          * Ano exibido no aviso de copyright. Ver `CURRENT_YEAR`.
          * @default CURRENT_YEAR
         */
        "year"?: number;
    }
    interface AppHeader {
        /**
          * @default 'storefront'
         */
        "activeZone"?: 'storefront' | 'blog';
        /**
          * @default false
         */
        "userLoggedIn"?: boolean;
    }

    interface AppFooterAttributes {
        "year": number;
    }
    interface AppHeaderAttributes {
        "activeZone": 'storefront' | 'blog';
        "userLoggedIn": boolean;
    }

    interface IntrinsicElements {
        "app-footer": Omit<AppFooter, keyof AppFooterAttributes> & { [K in keyof AppFooter & keyof AppFooterAttributes]?: AppFooter[K] } & { [K in keyof AppFooter & keyof AppFooterAttributes as `attr:${K}`]?: AppFooterAttributes[K] } & { [K in keyof AppFooter & keyof AppFooterAttributes as `prop:${K}`]?: AppFooter[K] };
        "app-header": Omit<AppHeader, keyof AppHeaderAttributes> & { [K in keyof AppHeader & keyof AppHeaderAttributes]?: AppHeader[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `attr:${K}`]?: AppHeaderAttributes[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `prop:${K}`]?: AppHeader[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.IntrinsicElements["app-footer"] & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.IntrinsicElements["app-header"] & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
        }
    }
}
